apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: infra.noobcloud.com.br
    http:
      paths:
      - path: /prometheus/?(.*)
        backend:
          serviceName: prometheus-service
          servicePort: 8080
